name: task_master
description: Manage tasks efficiently

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Networking
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.3.1

  # Routing
  auto_route: ^7.8.4

  # Utility
  uuid: ^4.3.3
  intl: ^0.18.0
  envied: ^0.5.3
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  flutter_bloc: ^8.1.5
  # Dependency Injection
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  flutter_form_builder: ^9.2.1
  intl_utils: ^2.8.7
  form_builder_validators: ^9.1.0
  flutter_animate: ^4.5.0
  infinite_scroll_pagination: ^4.0.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  # Linter
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: "^0.13.1"

  # Code Generation
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  auto_route_generator: ^7.3.2
  task_master_ui:
    path: ./lib/core/modules/task_master_ui
  task_master_storage:
    path: ./lib/core/modules/task_master_storage
  task_master_repo:
    path: ./lib/core/modules/task_master_repo

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_intl:
  enabled: true
  class_name: AppLocalizations